{{- if include "github-sts.createEndpointAuthSecret" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "github-sts.endpointAuthSecretName" . }}
  labels:
    {{- include "github-sts.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- with .Values.endpointAuth.healthToken }}
  {{ $.Values.endpointAuth.healthKey }}: {{ . | quote }}
  {{- end }}
  {{- with include "github-sts.endpointAuthMetricsToken" . }}
  {{ $.Values.endpointAuth.metricsKey }}: {{ . | quote }}
  {{- end }}
{{- end }}
