apiVersion: v1
kind: Service
metadata:
  name: {{ include "github-sts.fullname" . }}
  labels:
    {{- include "github-sts.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ include "github-sts.portName" . }}
      protocol: TCP
      name: {{ include "github-sts.portName" . }}
      {{- if .Values.service.appProtocol }}
      appProtocol: {{ .Values.service.appProtocol }}
      {{- else if .Values.tls.enabled }}
      appProtocol: https
      {{- end }}
  selector:
    {{- include "github-sts.selectorLabels" . | nindent 4 }}
